spring:
  application:
    name: State
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 9010
